services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: datalchemy
      POSTGRES_PASSWORD: datalchemy
      POSTGRES_DB: datalchemy
    ports:
      - "5432:5432"
    volumes:
      - ../fixtures/sql/postgres:/docker-entrypoint-initdb.d:ro
