[package]
name = "datalchemy-tools"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "gen_faker_catalog"
path = "gen_faker_catalog.rs"

[dependencies]
regex = "1.11.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
toml = "0.8.19"
